### ISSUE TITLE
React web frontend skeleton with three column grid and basic message input field

### ISSUE THREAD

**Issue by k4u5h1k** [dreadnoughtrobotics/DNT-chat-app#4]
![Screenshot 2021-03-22 at 4 33 18 PM](https://user-images.githubusercontent.com/59250093/111980443-51ac4b80-8b2c-11eb-8954-c0f1d70459e1.png)

Leftmost bar is for navigating channels
Middle bar is for sending and recieving messages on selected user/channel
Right bar is for activity status of your friends

**Comment by PratikGarai** [comment]
PR merged, will build on this skeleton for solving #3
